### ISSUE TITLE
pod install error 

### ISSUE THREAD

**Issue by dd9913762113** [LiteAVSDK/Player_Flutter#1]
[!] Error installing TXLiteAVSDK_Player
[!] /usr/bin/curl -f -L -o /var/folders/c5/chs7fvl52p947wp8htqzxjh40000gn/T/d20210717-86915-oqa2ds/file.zip https://liteav.sdk.qcloud.com/download/releases/8.9/TXLiteAVSDK_Player_iOS_8.9.10361.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.1 cocoapods-downloader/1.4.0'

**Comment by dokieyang** [comment]
请更新到最新版本试试
