### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by WANGNEWMAN** [LiteAVSDK/Player_Flutter#103]
Launching lib/main.dart on iPad Pro (11-inch) (4th generation) in debug mode...
Xcode build done.                                            5.8s
Failed to build iOS app
Error (Xcode): lib/superplayer_widget/lib/demo_superplayer_lib.dart:18:6: Error: The language version override has to be the same in the library and its part(s).

Could not build the application for the simulator.
Error launching application on iPad Pro (11-inch) (4th generation).

**Comment by Kongdy** [comment]
@WANGNEWMAN flutter版本或者三方库的不兼容问题，可以尝试执行 flutter pub update升级flutter依赖，或者将flutter sdk升级到3.7 以上的版本再试试

**Comment by Kongdy** [comment]
长时间未活动，关闭 issue
