### ISSUE TITLE
Namespace not specified,需要对AGP8.2以上的android版本插件做兼容。

### ISSUE THREAD

**Issue by lzhAndroid** [LiteAVSDK/Player_Flutter#104]
A problem occurred configuring project ':super_player'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

**Comment by lzhAndroid** [comment]
请在build.gradle中添加类似代码，兼容使用namespace的项目，AGP8.0以后强制使用namespace。
if (project.android.hasProperty("namespace")) { namespace ... })

**Comment by Kongdy** [comment]
@lzhAndroid 对高版本gradle支持已经完成，后续会发布更新

**Comment by Kongdy** [comment]
该问题已经于 [745fb3e817edeff11c7d8e5bdd93451ffe5bebbc](https://github.com/LiteAVSDK/Player_Flutter/commit/745fb3e817edeff11c7d8e5bdd93451ffe5bebbc) 版本修复
