### ISSUE TITLE
android 判断是否支持画中画有 bug

### ISSUE THREAD

**Issue by whichname** [LiteAVSDK/Player_Flutter#105]
```java
    public int isSupportDevice() {
        int pipResult = FTXEvent.NO_ERROR;
        Activity activity = mActivityBinding.getActivity();
        if (!activity.isDestroyed()) {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                // check permission
                boolean isSuccess =
                        activity.getPackageManager().hasSystemFeature(PackageManager.FEATURE_PICTURE_IN_PICTURE);
                if (!isSuccess) {
                    pipResult = FTXEvent.ERROR_PIP_DENIED_PERMISSION;
                    Log.e(TAG, "enterPip failed,because PIP feature is disabled");
                } else if (!hasPipPermission(activity)) {
                    pipResult = FTXEvent.ERROR_PIP_DENIED_PERMISSION;
                    Log.e(TAG, "enterPip failed,because PIP has no permission");
                }
            } else {
                pipResult = FTXEvent.ERROR_PIP_LOWER_VERSION;
                Log.e(TAG, "enterPip failed,because android version is too low,Minimum supported version is android "
                        + "24,but current is " + Build.VERSION.SDK_INT);
            }
        } else {
            pipResult = FTXEvent.ERROR_PIP_ACTIVITY_DESTROYED;
            Log.e(TAG, "enterPip failed,because activity is destroyed");
        }
        return pipResult;
    }

    private boolean hasPipPermission(Activity activity) {
        AppOpsManager appOpsManager = (AppOpsManager) activity.getSystemService(Context.APP_OPS_SERVICE);
        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
            int permissionResult = appOpsManager.checkOpNoThrow(AppOpsManager.OPSTR_PICTURE_IN_PICTURE,
                    android.os.Process.myUid(), activity.getPackageName());
            return permissionResult == AppOpsManager.MODE_ALLOWED;
        } else {
            return false;
        }
    }
```

如果当前为 API 24，相当于
```
    public int isSupportDevice() {
        int pipResult = FTXEvent.NO_ERROR;
        Activity activity = mActivityBinding.getActivity();
        if (!activity.isDestroyed()) {
            // 进这里
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                // 假如是 success
                boolean isSuccess =
                        activity.getPackageManager().hasSystemFeature(PackageManager.FEATURE_PICTURE_IN_PICTURE);
                if (!isSuccess) {
                    pipResult = FTXEvent.ERROR_PIP_DENIED_PERMISSION;
                    Log.e(TAG, "enterPip failed,because PIP feature is disabled");
                }
                // 进这里，hasPipPermission 始终返回 false，所以 pipResult 始终为 FTXEvent.ERROR_PIP_DENIED_PERMISSION
                else if (!hasPipPermission(activity)) {
                    pipResult = FTXEvent.ERROR_PIP_DENIED_PERMISSION;
                    Log.e(TAG, "enterPip failed,because PIP has no permission");
                }
            } else {
                pipResult = FTXEvent.ERROR_PIP_LOWER_VERSION;
                Log.e(TAG, "enterPip failed,because android version is too low,Minimum supported version is android "
                        + "24,but current is " + Build.VERSION.SDK_INT);
            }
        } else {
            pipResult = FTXEvent.ERROR_PIP_ACTIVITY_DESTROYED;
            Log.e(TAG, "enterPip failed,because activity is destroyed");
        }
        return pipResult;
    }
```

另外建议没权限跟不支持的判断可以分开，这样可以实现：
1. 不支持的时候隐藏画中画的开关
2. 没权限可以在用户点击后，弹窗提示或跳转到开启权限页面

现在没办法区分是不支持还是没权限

**Comment by Kongdy** [comment]
感谢你对flutter播放器的支持，我们会在后续版本对这里进行修改。







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiteAVSDK/Player_Flutter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月22日(星期三) 下午4:26
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[LiteAVSDK/Player_Flutter] android 判断是否支持画中画有 bug (Issue #105)





     public int isSupportDevice() {         int pipResult = FTXEvent.NO_ERROR;         Activity activity = mActivityBinding.getActivity();         if (!activity.isDestroyed()) {             if (Build.VERSION.SDK_INT &gt;= Build.VERSION_CODES.N) {                 // check permission                 boolean isSuccess =                         activity.getPackageManager().hasSystemFeature(PackageManager.FEATURE_PICTURE_IN_PICTURE);                 if (!isSuccess) {                     pipResult = FTXEvent.ERROR_PIP_DENIED_PERMISSION;                     Log.e(TAG, "enterPip failed,because PIP feature is disabled");                 } else if (!hasPipPermission(activity)) {                     pipResult = FTXEvent.ERROR_PIP_DENIED_PERMISSION;                     Log.e(TAG, "enterPip failed,because PIP has no permission");                 }             } else {                 pipResult = FTXEvent.ERROR_PIP_LOWER_VERSION;                 Log.e(TAG, "enterPip failed,because android version is too low,Minimum supported version is android "                         + "24,but current is " + Build.VERSION.SDK_INT);             }         } else {             pipResult = FTXEvent.ERROR_PIP_ACTIVITY_DESTROYED;             Log.e(TAG, "enterPip failed,because activity is destroyed");         }         return pipResult;     }     private boolean hasPipPermission(Activity activity) {         AppOpsManager appOpsManager = (AppOpsManager) activity.getSystemService(Context.APP_OPS_SERVICE);         if (android.os.Build.VERSION.SDK_INT &gt;= android.os.Build.VERSION_CODES.O) {             int permissionResult = appOpsManager.checkOpNoThrow(AppOpsManager.OPSTR_PICTURE_IN_PICTURE,                     android.os.Process.myUid(), activity.getPackageName());             return permissionResult == AppOpsManager.MODE_ALLOWED;         } else {             return false;         }     }
 
如果当前为 API 24，相当于
     public int isSupportDevice() {         int pipResult = FTXEvent.NO_ERROR;         Activity activity = mActivityBinding.getActivity();         if (!activity.isDestroyed()) {             // 进这里             if (Build.VERSION.SDK_INT &gt;= Build.VERSION_CODES.N) {                 // 假如是 success                 boolean isSuccess =                         activity.getPackageManager().hasSystemFeature(PackageManager.FEATURE_PICTURE_IN_PICTURE);                 if (!isSuccess) {                     pipResult = FTXEvent.ERROR_PIP_DENIED_PERMISSION;                     Log.e(TAG, "enterPip failed,because PIP feature is disabled");                 }                 // 进这里，hasPipPermission 始终返回 false，所以 pipResult 始终为 FTXEvent.ERROR_PIP_DENIED_PERMISSION                 else if (!hasPipPermission(activity)) {                     pipResult = FTXEvent.ERROR_PIP_DENIED_PERMISSION;                     Log.e(TAG, "enterPip failed,because PIP has no permission");                 }             } else {                 pipResult = FTXEvent.ERROR_PIP_LOWER_VERSION;                 Log.e(TAG, "enterPip failed,because android version is too low,Minimum supported version is android "                         + "24,but current is " + Build.VERSION.SDK_INT);             }         } else {             pipResult = FTXEvent.ERROR_PIP_ACTIVITY_DESTROYED;             Log.e(TAG, "enterPip failed,because activity is destroyed");         }         return pipResult;     }  
另外建议没权限跟不支持的判断可以分开，这样可以实现：
  
不支持的时候隐藏画中画的开关
 
没权限可以在用户点击后，弹窗提示或跳转到开启权限页面
  
现在没办法区分是不支持还是没权限

**Comment by Kongdy** [comment]
该问题已经于 [fa0fc48d54522554c36fb6029a7797b65478b7b8](https://github.com/LiteAVSDK/Player_Flutter/commit/fa0fc48d54522554c36fb6029a7797b65478b7b8) 提交修复
