### ISSUE TITLE
播放器加载地址后日志会有一个错误java.io.FileNotFoundException: https://drm.vodplayvideo.net/getlicense/v1?drmType=SimpleAES

### ISSUE THREAD

**Issue by SpielbergGao** [LiteAVSDK/Player_Flutter#108]
I/System.out( 6816): [OkHttp] sendRequest>>
I/System.out( 6816): [OkHttp] sendRequest<<
W/System.err( 6816): java.io.FileNotFoundException: https://drm.vodplayvideo.net/getlicense/v1?drmType=SimpleAES
W/System.err( 6816): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
W/System.err( 6816): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
W/System.err( 6816): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
W/System.err( 6816): 	at com.tencent.liteav.base.http.HttpClientAndroid.doReadData(SourceFile:665)
W/System.err( 6816): 	at com.tencent.liteav.base.http.HttpClientAndroid.doRequest(SourceFile:574)
W/System.err( 6816): 	at com.tencent.liteav.base.http.HttpClientAndroid.lambda$send$0(SourceFile:321)
W/System.err( 6816): 	at com.tencent.liteav.base.http.a.run(Unknown Source:4)
W/System.err( 6816): 	at android.os.Handler.handleCallback(Handler.java:942)
W/System.err( 6816): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err( 6816): 	at android.os.Looper.loopOnce(Looper.java:240)
W/System.err( 6816): 	at android.os.Looper.loop(Looper.java:351)
W/System.err( 6816): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/liteav  ( 6816): [E][06-12/08:37:44.727+8.0][6816,26005][log_jni.cc:42]HttpClientAndroid: (58290850)Do read data failed. Fail to get InputStream.
I/liteav  ( 6816): [I][06-12/08:37:44.727+8.0][6816,26005][log_jni.cc:30]tpdlcore: [SystemHttpLinkServer.cpp,496] [INFO][handleHttpEnd]LinkServer[6]. http end with error. http code: 1001. 
W/System.err( 6816): java.io.FileNotFoundException: https://drm.vodplayvideo.net/getlicense/v1?drmType=SimpleAES
I/liteav  ( 6816): [I][06-12/08:37:44.728+8.0][6816,26003][log_jni.cc:30]tpdlcore: [SystemHttpLinkServer.cpp,533] [INFO][responseToClient]LinkServer[6]. responseToClient[2 / 1], cacheRange[0, -1], state: 1, http code: 1001, body length: 0, data[-1--2]
W/System.err( 6816): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
W/System.err( 6816): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
W/System.err( 6816): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
E/liteav  ( 6816): [E][06-12/08:37:44.728+8.0][6816,26003][log_jni.cc:42]tpdlcore: [SystemHttpRequest.cpp,246] [ERROR][doEndResponse]doEndResponse error, responseCode: 1001
W/System.err( 6816): 	at com.tencent.liteav.base.http.HttpClientAndroid.closeConnectionSafely(SourceFile:531)
W/System.err( 6816): 	at com.tencent.liteav.base.http.HttpClientAndroid.doCallbackAndResetState(SourceFile:804)
W/System.err( 6816): 	at com.tencent.liteav.base.http.HttpClientAndroid.doReadData(SourceFile:671)
W/System.err( 6816): 	at com.tencent.liteav.base.http.HttpClientAndroid.doRequest(SourceFile:574)
W/System.err( 6816): 	at com.tencent.liteav.base.http.HttpClientAndroid.lambda$send$0(SourceFile:321)
W/System.err( 6816): 	at com.tencent.liteav.base.http.a.run(Unknown Source:4)
W/System.err( 6816): 	at android.os.Handler.handleCallback(Handler.java:942)
W/System.err( 6816): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err( 6816): 	at android.os.Looper.loopOnce(Looper.java:240)
W/System.err( 6816): 	at android.os.Looper.loop(Looper.java:351)
W/System.err( 6816): 	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by Kongdy** [comment]
@SpielbergGao 网络错误，可以检查和更换网络环境或者设备再次尝试下，如果有开启网络代理，可以关闭之后再尝试，如果还有问题，可以进一步描述复现场景和提供完整的播放器日志
