### ISSUE TITLE
华为鸿蒙4.2.0，画中画时切换到桌面，点击恢复全屏后，无法再次切换到画中画

### ISSUE THREAD

**Issue by whichname** [LiteAVSDK/Player_Flutter#109]
设备：华为 Mate Xs 2  
系统：鸿蒙 4.2.0
步骤：
1. 切换到画中画
2. 返回到桌面，此时画中画在播放
3. 点击画中画中的恢复全屏按钮
4. 恢复全屏后，再点击切换到画中画

表现：
1. 第二次切换到画中画时，无反应。其实是 startActivity 报错，控制台报错：`activity start fail: Background activity start`
2. 此时返回到桌面，画中画窗口会出现

**Comment by Kongdy** [comment]
@whichname 该问题已有规避方案，可以使用主干分支最新代码验证
