### ISSUE TITLE
App 异常崩溃

### ISSUE THREAD

**Issue by ZoeyGit** [LiteAVSDK/Player_Flutter#110]
E/AndroidRuntime(28629): java.lang.RuntimeException: Unable to destroy activity {com.zhikaodian.tk/com.zhikaodian.tk.wxapi.WXEntryActivity}: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
E/AndroidRuntime(28629): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6828)
E/AndroidRuntime(28629): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:6874)
E/AndroidRuntime(28629): 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:57)
E/AndroidRuntime(28629): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:50)
E/AndroidRuntime(28629): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:190)
E/AndroidRuntime(28629): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
E/AndroidRuntime(28629): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:3082)
E/AndroidRuntime(28629): 	at android.os.Handler.dispatchMessage(Handler.java:117)
E/AndroidRuntime(28629): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime(28629): 	at android.os.Looper.loop(Looper.java:293)
E/AndroidRuntime(28629): 	at android.app.ActivityThread.loopProcess(ActivityThread.java:9986)
E/AndroidRuntime(28629): 	at android.app.ActivityThread.main(ActivityThread.java:9975)
E/AndroidRuntime(28629): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28629): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
E/AndroidRuntime(28629): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1240)
E/AndroidRuntime(28629): Caused by: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
E/AndroidRuntime(28629): 	at java.util.ArrayList.remove(ArrayList.java:506)
E/AndroidRuntime(28629): 	at com.tencent.vod.flutter.tools.TXFlutterEngineHolder$1.onActivityDestroyed(TXFlutterEngineHolder.java:96)
E/AndroidRuntime(28629): 	at android.app.Application.dispatchActivityDestroyed(Application.java:549)
E/AndroidRuntime(28629): 	at android.app.Activity.dispatchActivityDestroyed(Activity.java:1601)
E/AndroidRuntime(28629): 	at android.app.Activity.onDestroy(Activity.java:2877)
E/AndroidRuntime(28629): 	at android.app.Activity.performDestroy(Activity.java:8875)
E/AndroidRuntime(28629): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1379)
E/AndroidRuntime(28629): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6815)
E/AndroidRuntime(28629): 	... 14 more

Flutter 3.22.2   dart 3.4.3 

APP进行微信登录、授权成功返回APP后 APP崩溃闪退 具体看日志是com.tencent.vod.flutter.tools.TXFlutterEngineHolde导致

**Comment by Kongdy** [comment]
该问题已于 [ae23cf02d96b1fb6f21cb826c762beb5d1d645ef](https://github.com/LiteAVSDK/Player_Flutter/commit/ae23cf02d96b1fb6f21cb826c762beb5d1d645ef) 提交修复
