### ISSUE TITLE
iOS播放暂停后，锁屏，过2分钟，通知栏点击，controller resume无效

### ISSUE THREAD

**Issue by lzhAndroid** [LiteAVSDK/Player_Flutter#112]
iOS播放锁屏，通知栏点击暂停，关闭屏幕，过2分钟，通知栏点击播放，播放调用controller的resume无效，重新生成新的controller，播放是可以的。希望尽快修复熄屏无法调用resume的问题

**Comment by lzhAndroid** [comment]
没有回复的么？

**Comment by Kongdy** [comment]
@lzhAndroid 锁屏一段时间后，播放器内核部分内部会被系统回收，导致无法播放，建议先重新生成播放器使用
