### ISSUE TITLE
iOS 什么时候能支持直播画中画播放

### ISSUE THREAD

**Issue by Xwnine** [LiteAVSDK/Player_Flutter#115]
看最新代码，iOS App内直播画中画依然是不支持，请问以后会支持吗？如果支持，有没有规划的时间点？

![image](https://github.com/user-attachments/assets/506d33a1-1def-4d08-8ac1-e80bd30d5bdc)

**Comment by Kongdy** [comment]
@Xwnine ios 已经支持直播画中画，可以更新主干最新代码使用

**Comment by ilmari-code** [comment]
> @Xwnine ios 已经支持直播画中画，可以更新主干最新代码使用

能否支持退出后台自动开启画中画功能呢
