### ISSUE TITLE
含 ui 的播放器，切换全屏时报错：Domain=UISceneErrorDomain Code=101

### ISSUE THREAD

**Issue by cnlf** [LiteAVSDK/Player_Flutter#116]
含 ui 的播放器，切换全屏时报错：Domain=UISceneErrorDomain Code=101 "None of the requested orientations are supported by the view controller. Requested: portrait; Supported: landscapeRight" UserInfo={NSLocalizedDescription=None of the requested orientations are supported by the view controller. Requested: portrait; Supported: landscapeRight}

官方的 demo 也有这个问题，请问怎么修复

**Comment by Kongdy** [comment]
@cnlf 参考官网文档，ios 端需要配置支持横屏
https://cloud.tencent.com/document/product/881/81252#.E6.B7.BB.E5.8A.A0.E5.8E.9F.E7.94.9F.E9.85.8D.E7.BD.AE
