### ISSUE TITLE
部分视频出现花屏

### ISSUE THREAD

**Issue by RandyWei** [LiteAVSDK/Player_Flutter#22]
iOS 版本接入过程中发现部分视频出现花屏，尝试在onPlayerPixelBuffer回调中将CVPixelBufferRef转为图片就已经花屏了，但在原生 sdk demo代码中视频正常。是否有解决方案？因为视频涉及版本问题，不好把链接发出来。
![Screen Shot 2021-11-17 at 10 08 39](https://user-images.githubusercontent.com/3961749/142096227-b52582fc-4b5b-433a-91ac-d4700152356a.png)

**Comment by RandyWei** [comment]
还有好像设置setPlayerPixelFormatType无效

**Comment by dokieyang** [comment]
最新版本已经解决，欢迎使用
