### ISSUE TITLE
OPPO手机, SuperPlayer 切换全屏播放报错 

### ISSUE THREAD

**Issue by fanlb** [LiteAVSDK/Player_Flutter#33]
E/flutter (13093): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, bad array lengths, null, java.lang.RuntimeException: bad array lengths
E/flutter (13093): 	at android.os.Parcel.readTypedArray(Parcel.java:3160)
E/flutter (13093): 	at android.view.IWindowSession$Stub$Proxy.addToDisplayAsUser(IWindowSession.java:1382)
E/flutter (13093): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1159)
E/flutter (13093): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:399)
E/flutter (13093): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:134)
E/flutter (13093): 	at android.app.Dialog.show(Dialog.java:363)
E/flutter (13093): 	at android.app.Presentation.show(Presentation.java:279)
E/flutter (13093): 	at io.flutter.plugin.platform.VirtualDisplayController.resize(VirtualDisplayController.java:161)
E/flutter (13093): 	at io.flutter.plugin.platform.PlatformViewsController$1.resizePlatformView(PlatformViewsController.java:290)
E/flutter (13093): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.resize(PlatformViewsChannel.java:141)
E/flutter (13093): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:65)
E/flutter (13093): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter (13093): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
E/flutter (13093): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$DartMessenger(DartMessenger.java:206)
E/flutter (13093): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$6ZD1MYkhaLxyPjtoFDxe45u43DI.run(Unknown Source:12)
E/flutter (13093): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (13093): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (13093): 	at android.os.Looper.loopOnce(Looper.java:233)
E/flutter (13093): 	at android.os.Looper.loop(Looper.java:344)
E/flutter (13093): 	at android.app.ActivityThread.main(ActivityThread.java:8171)
E/flutter (13093): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (13093): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/flutter (13093): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
E/flutter (13093): )
E/flutter (13093): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (13093): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter (13093): <asynchronous suspension>
E/flutter (13093): #2      TextureAndroidViewController.setSize (package:flutter/src/services/platform_views.dart:1027:5)
E/flutter (13093): <asynchronous suspension>
E/flutter (13093): #3      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:191:7)
E/flutter (13093): <asynchronous suspension>

运行环境:

![image](https://user-images.githubusercontent.com/6261608/154875569-4d7f92d2-747d-4e5d-b885-58e175cac88f.png)
[从launcher启动app到back退出的完整日志.log](https://github.com/tencentyun/SuperPlayer/files/8105547/launcher.app.back.log)

**Comment by dokieyang** [comment]
新版本已经修复，欢迎使用
