### ISSUE TITLE
这个界面的demo在哪里

### ISSUE THREAD

**Issue by songguowei** [LiteAVSDK/Player_Flutter#35]
https://camo.githubusercontent.com/cc47060e2e1ac24cd92c09973ddfc6d5a5f9ef459106327d4c6961503c09394c/68747470733a2f2f6d632e71636c6f7564696d672e636f6d2f7374617469632f696d672f36616335653266653837653634326536633265363334326437323436346634612f696d6167652e706e67

这个

**Comment by dokieyang** [comment]
现在demo 里面提供了superPlayer，功能和上图非常类似，欢迎试用
