### ISSUE TITLE
知道是什么错误？

### ISSUE THREAD

**Issue by Gagoooooo** [LiteAVSDK/Player_Flutter#37]
/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:114: error: package com.example.super_player does not exist
      flutterEngine.getPlugins().add(new com.example.super_player.SuperPlayerPlugin());
                                                                 ^
1 error

**Comment by dokieyang** [comment]
新版本已经修复，欢迎使用
