### ISSUE TITLE
请问这个播放器能实现ios端后台播放视频吗

### ISSUE THREAD

**Issue by lan2000** [LiteAVSDK/Player_Flutter#39]
请问这个播放器能实现ios端后台播放视频吗？看不到画面，起码能听到播放的声音。能实现吗？

**Comment by Aikoia** [comment]
> 请问这个播放器能实现ios端后台播放视频吗？看不到画面，起码能听到播放的声音。能实现吗？

请问一下你解决了吗？

**Comment by lan2000** [comment]
> 
解决了，你完成下面步骤试试
https://www.jianshu.com/p/71ab0e828c0a
1. 修改 Info.plist
2. 修改 Capabilities
