### ISSUE TITLE
会有内存溢出问题

### ISSUE THREAD

**Issue by RmondJone** [LiteAVSDK/Player_Flutter#4]
如果一直新开点播页面，会内存会一直涨，最终导致白屏

**Comment by steve0755** [comment]
android还是ios，能提供更多详细的信息吗？
我这边试了我们的demo，未发现会出现内存一直涨的问题。

**Comment by RmondJone** [comment]
我用的是Flutter版本的SDK，都会有

**Comment by dokieyang** [comment]
新版本已经修复，欢迎使用，还有问题的话，请反馈给我们，谢谢
