### ISSUE TITLE
import com.tencent.rtmp.TXLog;错误: 找不到符号

### ISSUE THREAD

**Issue by yongjieYuan** [LiteAVSDK/Player_Flutter#43]
android\superplayerkit\src\main\java\com\tencent\liteav\demo\superplayer\model\utils\NetWatcher.java:12: 错误: 找不到符号

之前运行项目是可以的，突然说是找不到TXLog，是什么原因呢

![微信截图_20220601103248](https://user-images.githubusercontent.com/56886417/171316227-ccb181ec-88ed-491e-b4f6-2370ddaf9a4d.png)

**Comment by dokieyang** [comment]
你好，版本升级把TXLog去掉了， 请你升级到最新版本即可。
