### ISSUE TITLE
播放器的状态监听

### ISSUE THREAD

**Issue by AlanJN** [LiteAVSDK/Player_Flutter#44]
_controller.onPlayerState.listen 这个监听，从暂停状态到播放状态，不会执行，从播放状态到暂停状态会执行。

**Comment by dokieyang** [comment]
请问你要监听这个事件的需求是什么
暂停到开始播放，会有事件：TXVodPlayEvent.PLAY_EVT_PLAY_BEGIN 回调，可以通过下面接口监听：_vodPlayerController?.onPlayerEventBroadcast?.listen
