### ISSUE TITLE
Transform's input file does not exist

### ISSUE THREAD

**Issue by appsw** [LiteAVSDK/Player_Flutter#46]
//此处仅处理因插件项目内报红显示的处理方式
compileOnly files("$flutterRoot/bin/cache/artifacts/engine/android-arm/flutter.jar")
这句代码会导致下面的错误
* What went wrong:
Execution failed for task ':super_player:compileReleaseJavaWithJavac'.
> Could not resolve all files for configuration ':super_player:releaseCompileClasspath'.
   > Failed to transform flutter.jar to match attributes {artifactType=android-classes-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: /Users/apple/fvm/versions/2.10.3/bin/cache/artifacts/engine/android-arm/flutter.jar.
         > Transform's input file does not exist: /Users/apple/fvm/versions/2.10.3/bin/cache/artifacts/engine/android-arm/flutter.jar.

**Comment by Kongdy** [comment]
可以先注掉，这个只是用于在编写过程中规避掉代码报红问题，在不同环境配置下改jar包路径可能不一样。后续会去掉改引用

**Comment by dokieyang** [comment]
最新版本已经解决，欢迎使用
