### ISSUE TITLE
Android端，视频播放只有画面，没有声音

### ISSUE THREAD

**Issue by zhuhonglei** [LiteAVSDK/Player_Flutter#47]
测试地址：http://app.grelighting.cn/m3u8/d0dJMDB0eDgzRGl4YkN0QnVXSmRTQ0VEZkJsMkVxeHYyZE5TMFk3aWNSST0=.m3u8

**Comment by Tonigt** [comment]
ios 音频解码失败  Error decoding audio stream: 1650549857

**Comment by Tonigt** [comment]
[ac]   ACMP4AACBaseDecoder.cpp:1438  (0x106566440) Error decoding packet 2367: err = -1, packet length: 124
[ac]   ACMP4AACBaseDecoder.cpp:1447  '21 18 14 7D 1D 8C A3 62 C0 98 62 66 71 DE 6F 57 C2 49 4C B8 94 90 84 94 12 AB 49 62 F3 5A 0D 30 DA 08 7C AA AB 07 97 9B D2 55 EF F8 65 DB 65 25 AA 99 A2 4C EA D9 84 59 3F C7 BA 6B DC D2 C7 A9 22 E1 0A E0 46 74 14 B2 D8 1C C9 CB 78 80 83 52 CD 12 11 4A 00 A3 03 C2 A2 12 BA 23 EF 04 67 26 08 04 41 56 81 C4 5C 25 F6 ED 8F 0A F3 02 2E 80 59 B1 A6 B4 15 B5 4D E0 AC 0F 84 70'
[E][TXCHWAACDecoder.mm, decodeAudioFrame, 140]:Error decoding audio stream: 1650549857
 Too few bits left in input buffer
 Error deserializing packet

**Comment by dokieyang** [comment]
新版本已经解决
