### ISSUE TITLE
Undefined class 'SuperPlayerController'.

### ISSUE THREAD

**Issue by yongjieYuan** [LiteAVSDK/Player_Flutter#48]
文件引入了superplayer,
import 'package:super_player/super_player.dart';

但是使用的时候没有找到：Undefined class 'SuperPlayerController'.

**Comment by yongjieYuan** [comment]
抱歉，没有太仔细看，超级播放器是不是要自己去集成的呢？我把example的superplayer ui文件夹单独拿出来使用，是可以用的。

**Comment by dokieyang** [comment]
> Reference
对的，请参考我们的集成指引：https://github.com/LiteAVSDK/Player_Flutter/tree/main/Flutter#%E6%B7%B1%E5%BA%A6%E5%AE%9A%E5%88%B6%E5%BC%80%E5%8F%91%E6%8C%87%E5%BC%95
