### ISSUE TITLE
添加后，IOS端报 Framework not found TXFFmpeg

### ISSUE THREAD

**Issue by clstech** [LiteAVSDK/Player_Flutter#49]
`Launching lib/main.dart on iPhone 12 Pro in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           10.1s
Failed to build iOS app
Error output from Xcode build:
↳
    2022-06-29 20:11:47.676 xcodebuild[6648:361992] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    2022-06-29 20:11:47.676 xcodebuild[6648:361992] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    ** BUILD FAILED **

Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/_7/p7q8gh35583fx7nd61462fkm0000gn/T/flutter_tools.Xk77uQ/flutter_ios_build_temp_dirliCnIP/temporary_xcresult_bundle

    warning: [CP] TXSoundTouch.xcframework: Unable to find matching slice in 'ios-x86_64-simulator ios-arm64_armv7' for the current build architectures (arm64 x86_64 i386) and platform (-iphonesimulator).
    warning: [CP] TXFFmpeg.xcframework: Unable to find matching slice in 'ios-x86_64-simulator ios-arm64_armv7' for the current build architectures (arm64 x86_64 i386) and platform (-iphonesimulator).
    While building module 'TXLiteAVSDK_Professional' imported from /Users/chenchun/.pub-cache/git/SuperPlayer-7bc259aa93d008be6f0e17130a4b2f216166a6aa/Flutter/ios/Classes/FTXTransformation.h:3:
    In file included from <module-includes>:1:
    In file included from /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TXLiteAVSDK.h:12:
    In file included from /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TRTCCloud.h:10:
    /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TRTCCloudDelegate.h:255:11: warning: parameter 'extrainfo' not found in the function declaration [-Wdocumentation]
     * @param extrainfo 额外信息
              ^~~~~~~~~
    /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TRTCCloudDelegate.h:255:11: note: did you mean 'info'?
     * @param extrainfo 额外信息
              ^~~~~~~~~
              info
    While building module 'TXLiteAVSDK_Professional' imported from /Users/chenchun/.pub-cache/git/SuperPlayer-7bc259aa93d008be6f0e17130a4b2f216166a6aa/Flutter/ios/Classes/FTXTransformation.h:3:
    In file included from <module-includes>:1:
    In file included from /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TXLiteAVSDK.h:19:
    In file included from /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TXLivePlayer.h:6:
    /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TXLivePlayListener.h:13:11: warning: parameter 'EvtID' not found in the function declaration [-Wdocumentation]
     * @param EvtID 参见 TXLiveSDKEventDef.h
              ^~~~~
    /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TXLivePlayListener.h:13:11: note: did you mean 'evtID'?
     * @param EvtID 参见 TXLiveSDKEventDef.h
              ^~~~~
              evtID
    While building module 'TXLiteAVSDK_Professional' imported from /Users/chenchun/.pub-cache/git/SuperPlayer-7bc259aa93d008be6f0e17130a4b2f216166a6aa/Flutter/ios/Classes/FTXTransformation.h:3:
    In file included from <module-includes>:1:
    In file included from /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TXLiteAVSDK.h:38:
    /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TXVodPlayer.h:166:11: warning: parameter 'mode' not found in the function declaration [-Wdocumentation]
     * @param mode 填充（画面可能会被拉伸裁剪）或适应（画面可能会有黑边），默认值：TRTCVideoFillMode_Fit
              ^~~~
    /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TXVodPlayer.h:166:11: note: did you mean 'renderMode'?
     * @param mode 填充（画面可能会被拉伸裁剪）或适应（画面可能会有黑边），默认值：TRTCVideoFillMode_Fit
              ^~~~
              renderMode
    While building module 'TXLiteAVSDK_Professional' imported from /Users/chenchun/.pub-cache/git/SuperPlayer-7bc259aa93d008be6f0e17130a4b2f216166a6aa/Flutter/ios/Classes/FTXTransformation.h:3:
    In file included from <module-includes>:1:
    In file included from /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TXLiteAVSDK.h:49:
    In file included from /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TXLivePush.h:21:
    /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TXLivePushListener.h:19:11: warning: parameter 'EvtID' not found in the function declaration [-Wdocumentation]
     * @param EvtID 参见 TXLiveSDKEventDef.h
              ^~~~~
    /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TXLivePushListener.h:19:11: note: did you mean 'evtID'?
     * @param EvtID 参见 TXLiveSDKEventDef.h
              ^~~~~
              evtID
    While building module 'TXLiteAVSDK_Professional' imported from /Users/chenchun/.pub-cache/git/SuperPlayer-7bc259aa93d008be6f0e17130a4b2f216166a6aa/Flutter/ios/Classes/FTXTransformation.h:3:
    In file included from <module-includes>:1:
    /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TXLiteAVSDK.h:61:1: warning: umbrella header for module 'TXLiteAVSDK_Professional' does not include header '/cpp_interface/ITRTCCloud.h' [-Wincomplete-umbrella]
    /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TXLiteAVSDK.h:61:1: warning: umbrella header for module 'TXLiteAVSDK_Professional' does not include header '/cpp_interface/IDeprecatedTRTCCloud.h' [-Wincomplete-umbrella]
    /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TXLiteAVSDK.h:61:1: warning: umbrella header for module 'TXLiteAVSDK_Professional' does not include header '/cpp_interface/TRTCCloudCallback.h' [-Wincomplete-umbrella]
    /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TXLiteAVSDK.h:61:1: warning: umbrella header for module 'TXLiteAVSDK_Professional' does not include header '/cpp_interface/TRTCTypeDef.h' [-Wincomplete-umbrella]
    /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TXLiteAVSDK.h:61:1: warning: umbrella header for module 'TXLiteAVSDK_Professional' does not include header '/cpp_interface/ITRTCStatistics.h' [-Wincomplete-umbrella]
    /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TXLiteAVSDK.h:61:1: warning: umbrella header for module 'TXLiteAVSDK_Professional' does not include header '/cpp_interface/TXLiteAVCode.h' [-Wincomplete-umbrella]
    /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TXLiteAVSDK.h:61:1: warning: umbrella header for module 'TXLiteAVSDK_Professional' does not include header '/cpp_interface/ITXAudioEffectManager.h' [-Wincomplete-umbrella]
    /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TXLiteAVSDK.h:61:1: warning: umbrella header for module 'TXLiteAVSDK_Professional' does not include header '/cpp_interface/ITXDeviceManager.h' [-Wincomplete-umbrella]
    12 warnings generated.
    12 warnings generated.
    12 warnings generated.
    While building module 'super_player' imported from /Users/chenchun/StudioProjects/demo/ios/Runner/GeneratedPluginRegistrant.m:10:
    While building module 'TXLiteAVSDK_Professional' imported from /Users/chenchun/StudioProjects/demo/build/ios/Debug-iphonesimulator/super_player/super_player.framework/Headers/FTXTransformation.h:3:
    In file included from <module-includes>:1:
    /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TXLiteAVSDK.h:61:1: warning: umbrella header for module 'TXLiteAVSDK_Professional' does not include header '/cpp_interface/ITRTCCloud.h' [-Wincomplete-umbrella]
    /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TXLiteAVSDK.h:61:1: warning: umbrella header for module 'TXLiteAVSDK_Professional' does not include header '/cpp_interface/IDeprecatedTRTCCloud.h' [-Wincomplete-umbrella]
    /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TXLiteAVSDK.h:61:1: warning: umbrella header for module 'TXLiteAVSDK_Professional' does not include header '/cpp_interface/TRTCCloudCallback.h' [-Wincomplete-umbrella]
    /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TXLiteAVSDK.h:61:1: warning: umbrella header for module 'TXLiteAVSDK_Professional' does not include header '/cpp_interface/TRTCTypeDef.h' [-Wincomplete-umbrella]
    /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TXLiteAVSDK.h:61:1: warning: umbrella header for module 'TXLiteAVSDK_Professional' does not include header '/cpp_interface/ITRTCStatistics.h' [-Wincomplete-umbrella]
    /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TXLiteAVSDK.h:61:1: warning: umbrella header for module 'TXLiteAVSDK_Professional' does not include header '/cpp_interface/TXLiteAVCode.h' [-Wincomplete-umbrella]
    /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TXLiteAVSDK.h:61:1: warning: umbrella header for module 'TXLiteAVSDK_Professional' does not include header '/cpp_interface/ITXAudioEffectManager.h' [-Wincomplete-umbrella]
    /Users/chenchun/StudioProjects/demo/ios/Pods/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional/TXLiteAVSDK_Professional.framework/Headers/TXLiteAVSDK.h:61:1: warning: umbrella header for module 'TXLiteAVSDK_Professional' does not include header '/cpp_interface/ITXDeviceManager.h' [-Wincomplete-umbrella]
    8 warnings generated.
    8 warnings generated.
    8 warnings generated.
    ld: framework not found TXFFmpeg
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    /Users/chenchun/StudioProjects/demo/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.5.99. (in target 'TXLiteAVSDK_Professional' from project 'Pods')

    Result bundle written to path:
    	/var/folders/_7/p7q8gh35583fx7nd61462fkm0000gn/T/flutter_tools.Xk77uQ/flutter_ios_build_temp_dirliCnIP/temporary_xcresult_bundle

Error (Xcode): Framework not found TXFFmpeg

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro.
`

**Comment by clstech** [comment]
操作之后，里面包含TXFFmpeg Framework

但会报

`Launching lib/main.dart on iPhone 12 Pro in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                            5.3s
Failed to build iOS app
Error output from Xcode build:
↳
    2022-06-29 22:19:24.381 xcodebuild[57061:190792] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    2022-06-29 22:19:24.382 xcodebuild[57061:190792] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/_7/p7q8gh35583fx7nd61462fkm0000gn/T/flutter_tools.bRtd4K/flutter_ios_build_temp_diryqzXPX/temporary_xcresult_bundle

    warning: [CP] TXSoundTouch.xcframework: Unable to find matching slice in 'ios-x86_64-simulator ios-arm64_armv7' for the current build architectures (arm64 x86_64 i386) and platform (-iphonesimulator).
    warning: [CP] TXFFmpeg.xcframework: Unable to find matching slice in 'ios-x86_64-simulator ios-arm64_armv7' for the current build architectures (arm64 x86_64 i386) and platform (-iphonesimulator).
    ld: framework not found TXFFmpeg
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    /Users/chenchun/StudioProjects/like/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.5.99. (in target 'ReachabilitySwift' from project 'Pods')
    /Users/chenchun/StudioProjects/like/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.5.99. (in target 'TXLiteAVSDK_Professional' from project 'Pods')

    Result bundle written to path:
    	/var/folders/_7/p7q8gh35583fx7nd61462fkm0000gn/T/flutter_tools.bRtd4K/flutter_ios_build_temp_diryqzXPX/temporary_xcresult_bundle


Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code

Error (Xcode): Framework not found TXFFmpeg

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro.
`

尝试将所有三方库的部署版本号强制修改到9.0后依然不行

**Comment by ljxt-pyd** [comment]
我是把项目里的iOS文件夹替换为example/iOS的文件解决的

**Comment by clstech** [comment]
> 我是把项目里的iOS文件夹替换为example/iOS的文件解决的

我替换后也是没能解决
