### ISSUE TITLE
安卓按照提示添加 tools:replace="android:label 报错

### ISSUE THREAD

**Issue by haijiao01** [LiteAVSDK/Player_Flutter#55]
Execution failed for task ':app:generateDebugBuildConfig'.
> Error while evaluating property 'namespace' of task ':app:generateDebugBuildConfig'
   > Failed to calculate the value of task ':app:generateDebugBuildConfig' property 'namespace'.
      > Failed to calculate the value of property 'namespace'.

**Comment by Kongdy** [comment]
manifest使用的时候，需要添加对应的命名空间，尝试在 manifest根节点增加如下属性
xmlns:tools="http://schemas.android.com/tools"
