### ISSUE TITLE
短视频效果上下滑动的时候，封面图不能及时更新，甚至有时候有声音有封面图，无视频画面

### ISSUE THREAD

**Issue by ywda** [LiteAVSDK/Player_Flutter#57]
短视频效果上下滑动的时候，封面图不能及时更新，甚至有时候有声音有封面图，无视频画面。
你们有没有遇到过？

这是我的资源：
**所使用的播放视频以及封面图 如下**
List<SuperPlayerModel> videoDataList = [];

 // 视频地址 2
    var videoList = [
      'test-video-10.MP4',

      // 'test-video-10.MP4',
      // 'test-video-10.MP4',
      // 'test-video-10.MP4',
      // 'test-video-10.MP4',
      // 'test-video-10.MP4',
      // 'test-video-10.MP4',
      // 'test-video-10.MP4',
      // 'test-video-10.MP4',

      'test-video-6.mp4',
      'test-video-9.MP4',
      'test-video-8.MP4',
      'test-video-7.MP4',
      'test-video-1.mp4',
      'test-video-2.mp4',
      'test-video-3.mp4',
      'test-video-4.mp4',
    ];

    List tmp = videoList
        .map((e) {
      SuperPlayerModel mode = SuperPlayerModel();
      mode.title = e;
      mode.customeCoverUrl = "https://cms-bucket.nosdn.127.net/cb37178af1584c1588f4a01e5ecf323120180418133127.jpeg";
      mode.videoURL = 'https://static.ybhospital.net/$e';
      mode.playAction = SuperPlayerModel.PLAY_ACTION_AUTO_PLAY;

      videoModels.add(mode);
      return mode;
    }).toList();

    for (var element in tmp) {
      videoModels.add(element);
    }

**flutter doctor 如下**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.69.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.

**我的主要代码**

    return WillPopScope(onWillPop: onWillPop, child: TikTokScaffold(
      controller: tkController,
      hasBottomPadding: hasBackground,
      tabBar: Container(height: 0,),
      header: Container(height: 0,),
      leftPage: null,
      rightPage: null,
      enableGesture: false,
      page: Stack(
        children: <Widget>[
          PageView.builder(
            key: const Key('home'),
            physics: const QuickerScrollPhysics(),
            controller: _pageController,
            scrollDirection: Axis.vertical,
            itemCount: videoDataList.length,
            itemBuilder: (context, i)  {
              // 拼一个视频组件出来
              bool isF = SafeMap(favoriteMap)[i].boolean;
              _controller.playWithModel(videoDataList[i]);
              return Container(
                decoration: const BoxDecoration(color: Colors.black),
                height: _controller.videoHeight, //MediaQuery.of(context).size.height,
                width: _controller.videoWidth,
                child: SuperPlayerView(_controller),
              );
            },
          ),
          currentPage ?? Container(),
          Positioned(top:MediaQuery.of(context).padding.top,left: 10, child: GestureDetector(child: Container(width: 50,height: 50,color: Colors.transparent,child: Icon(
            Icons.arrow_back_ios_new,
            size: 24,
            color: Colors.white.withOpacity(0.85),
          )),onTap: ()=> Navigator.of(context).pop(),)),
        ],
      ),
    ));}Future<bool> onWillPop() async {
    return !_controller.onBackPress();}

主要就是用了 PageView 做上下滑动的实现，视频数据源数组控制了 PageView 的可滑动屏个数，滑动后在 PageView.builder 的itemBuilder 下进行了切换播放器资源

**Comment by Kongdy** [comment]
可以参考demo中的短视频demo

**Comment by Linzehua2015** [comment]
这问题我也遇到了，我通过视频播放进度回调（这个时候一定是在播放）的时候才去隐藏封面。

**Comment by Linzehua2015** [comment]
还有另外个问题，获取到视频第一帧回调了，这个时候我去隐藏封面，但player展示是黑的，这个时间很短暂，但是给用户的体验就是看到封面到播放视频之间黑了一下，特别难受。

**Comment by dokieyang** [comment]
请试试example 里面的短视demo
