### ISSUE TITLE
播放器调stop(isNeedClear:true)不清屏

### ISSUE THREAD

**Issue by shuaigezhong** [LiteAVSDK/Player_Flutter#61]
调用stop()方法，不清屏。。。

**Comment by yjt1216** [comment]
null safe 
你引入super_player 有没有报null safe问题
我这flutter 15 会报这个问题，虽然可以本地 添加 null safe

**Comment by Kongdy** [comment]
@shuaigezhong 由于flutter播放器纹理位于flutter端，目前还不能清除该纹理，后续会考虑对该能力的支持。目前可以在业务上采用stop后更换flutter纹理的方式来清除

**Comment by Kongdy** [comment]
@yjt1216 建议建立新issue，能够详细描述问题并针对进行解答哈

**Comment by yjt1216** [comment]
> @yjt1216 建议建立新issue，能够详细描述问题并针对进行解答哈

已经处理了

**Comment by Kongdy** [comment]
时间长未回复，关闭
