### ISSUE TITLE
#36014 java.lang.NullPointerException Attempt to invoke virtual method 'android.content.Context io.flutter.embedding.engine.plugins.FlutterPlugin$FlutterPluginBinding.getApplicationContext()' on a null object reference  com.tencent.vod.flutter.SuperPlayerPlugin.isAutoRotateOn(SuperPlayerPlugin.java:282)

### ISSUE THREAD

**Issue by bladeofgod** [LiteAVSDK/Player_Flutter#63]
#36014 java.lang.NullPointerException
Attempt to invoke virtual method 'android.content.Context io.flutter.embedding.engine.plugins.FlutterPlugin$FlutterPluginBinding.getApplicationContext()' on a null object reference

com.tencent.vod.flutter.SuperPlayerPlugin.isAutoRotateOn(SuperPlayerPlugin.java:282)

1
com.tencent.vod.flutter.SuperPlayerPlugin.isAutoRotateOn(SuperPlayerPlugin.java:286)
2
com.tencent.vod.flutter.SuperPlayerPlugin$3.onOrientationChanged(SuperPlayerPlugin.java:102)
3
android.view.OrientationEventListener$SensorEventListenerImpl.onSensorChanged(OrientationEventListener.java:166)
4
android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:927)
5
android.os.MessageQueue.nativePollOnce(Native Method)
6
android.os.MessageQueue.next(MessageQueue.java:374)
7
android.os.Looper.loop(Looper.java:185)
8
android.app.ActivityThread.main(ActivityThread.java:9105)
9
java.lang.reflect.Method.invoke(Native Method)
10
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:614)
11
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1129)

**Comment by dokieyang** [comment]
最新版已经修复了，麻烦更新体验下
