### ISSUE TITLE
iOS crash, 播放m3u8视频时有概率出现野指针报错

### ISSUE THREAD

**Issue by HelloBie** [LiteAVSDK/Player_Flutter#65]
FTXVodPlayer ：
...
else if([@"play" isEqualToString:call.method]){
        NSString *url = args[@"url"];
        int r = [self startPlay:url];          //Thread 1: EXC_BAD_ACCESS (code=257, address=0x1)
        result(@(r));
    }
...

**Comment by dokieyang** [comment]
请问可以提供详细的堆栈信息吗

**Comment by HelloBie** [comment]
#52 TPDecoder#0#2

SIGSEGV



SEGV_ACCERR

解析原始
0
Flutter
0x00000001056fc000 + 77356
1
Runner
tpdlproxy::BaseTaskScheduler::CmpByValue(std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&, std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&) + 7867688
2
Runner
tpdlproxy::BaseTaskScheduler::CmpByValue(std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&, std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&) + 7867688
3
Runner
__cxa_throw + 684524
4
Runner
__cxa_throw + 668184
5
Runner
tpdlproxy::BaseTaskScheduler::CmpByValue(std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&, std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&) + 7035424
6
Runner
tpdlproxy::BaseTaskScheduler::CmpByValue(std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&, std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&) + 464488
7
Runner
tpdlproxy::BaseTaskScheduler::CmpByValue(std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&, std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&) + 968328
8
Runner
tpdlproxy::BaseTaskScheduler::CmpByValue(std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&, std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&) + 405868
9
Runner
tpdlproxy::BaseTaskScheduler::CmpByValue(std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&, std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&) + 1213576
10
Runner
tpdlproxy::BaseTaskScheduler::CmpByValue(std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&, std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&) + 1721844
11
Runner
tpdlproxy::BaseTaskScheduler::CmpByValue(std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&, std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&) + 1715940
12
Runner
tpdlproxy::BaseTaskScheduler::CmpByValue(std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&, std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&) + 1715124
13
Runner
tpdlproxy::BaseTaskScheduler::CmpByValue(std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&, std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&) + 1310800
14
Runner
tpdlproxy::BaseTaskScheduler::CmpByValue(std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&, std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&) + 1310560
15
Runner
tpdlproxy::BaseTaskScheduler::CmpByValue(std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&, std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&) + 2093352
16
Runner
tpdlproxy::BaseTaskScheduler::CmpByValue(std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&, std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&) + 2095300
17
Runner
tpdlproxy::BaseTaskScheduler::CmpByValue(std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&, std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const&) + 2095228
18
libsystem_pthread.dylib
__pthread_start + 148

**Comment by tgitpushping** [comment]
用的是什么版本？

**Comment by HelloBie** [comment]
> 用的是什么版本？
xcode :14.0.1
ios：swift
flutter : 3.0.1
release/release_pro_v1.0.6

**Comment by dokieyang** [comment]
最新版本已经修复了， 可以更新试试
 ref: [release_pro_v1.0.7](https://github.com/LiteAVSDK/Player_Flutter/releases/tag/release_pro_v1.0.7)
