### ISSUE TITLE
在IOS播放苹果手机拍摄的视频，视频角度会旋转90度

### ISSUE THREAD

**Issue by HongZhiQing** [LiteAVSDK/Player_Flutter#67]
![IMG_F0E6E1C979C2-1](https://user-images.githubusercontent.com/37497239/199638787-0088de77-b827-4c8d-8bb4-38460e05fad0.jpeg)
原视频：

https://user-images.githubusercontent.com/37497239/199638865-bb451dec-a69c-442c-ab0b-28feee005b32.mov

**Comment by Kongdy** [comment]
哪个版本？

**Comment by HongZhiQing** [comment]
> 哪个版本？

Professional

**Comment by HongZhiQing** [comment]
> 哪个版本？

SDK版本为10.7.11936

**Comment by Kongdy** [comment]
@HongZhiQing 使用的Play_flutter 是 10.7吗？

**Comment by Kongdy** [comment]
@HongZhiQing 使用的Player_Flutter 是 pro_1.0.7吗？

**Comment by HongZhiQing** [comment]
> 

不是   1.0.3

**Comment by dokieyang** [comment]
10.8 已经修复了，麻烦更新到最新版本试试
