### ISSUE TITLE
短视频内存不回收

### ISSUE THREAD

**Issue by Linzehua2015** [LiteAVSDK/Player_Flutter#68]
我的应用集成这个sdk后，短视频播放多了会内存溢出。
使用demo播放短视频发现也有这个问题，看完视频，返回上一级页面，内存不下降，视频看多了内存会一直增加。

**Comment by dokieyang** [comment]
请问是iOS 还是 Android端的问题呢
你使用的短视频是我们demo自带的吗

**Comment by Kongdy** [comment]
该问题已在10.8版本修复
