### ISSUE TITLE
Flutter pub get 无法拉取

### ISSUE THREAD

**Issue by yongjieYuan** [LiteAVSDK/Player_Flutter#69]
# pub get 无法拉取
![image](https://user-images.githubusercontent.com/56886417/203915389-49473154-dfdf-49e1-8846-3e00454c40fd.png)

## pubspec.yaml
  super_player:
    git:
      url: https://github.com/LiteAVSDK/Player_Flutter
      path: Flutter
==== 
Git error. Command: `git rev-list --max-count=1 HEAD`
stdout: 
stderr: usage: git rev-list [<options>] <commit-id>... [-- <path>...]
  limiting output:
    --max-count=<n>
    --max-age=<epoch>
    --min-age=<epoch>
    --sparse
    --no-merges
    --min-parents=<n>
    --no-min-parents
    --max-parents=<n>
    --no-max-parents
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --[no-]object-names
    --abbrev=<n> | --no-abbrev
    --abbrev-commit
    --left-right
    --count
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all
exit code: 129
pub finished with exit code 69
Process finished with exit code 69

**Comment by yongjieYuan** [comment]
已将项目下载到本地依赖，可否看看为什么使用pub get 的方式不行呢

**Comment by dokieyang** [comment]
从日志看不出为什么会拉取失败
建议清楚掉缓存后试试
