### ISSUE TITLE
华为手机播放闪屏白屏

### ISSUE THREAD

**Issue by DspringL** [LiteAVSDK/Player_Flutter#70]
如题，环境如下：
Flutter SDK：3.3.9
LiteAVSDK：release_pro_1.0.7
Phone：华为P30 pro，华为Mate 30Pro 等华为手机均出现闪屏、白屏等

**Comment by Kongdy** [comment]
@DspringL 目前使用官方demo、Flutter SDK 3.3.9、release_pro_1.0.7在华为P30 pro、mate 30Pro中均未复现，麻烦确认下是否是特定视频才会复现，可以将复现视频放在demo中播放看是否复现。如果仍然有问题，麻烦将复现视频源、复现方式以及log发到这里

**Comment by Kongdy** [comment]
长时间未回复，关闭issue
