### ISSUE TITLE
将FlatButton更改为TextButton后，无法播放

### ISSUE THREAD

**Issue by qadan72** [LiteAVSDK/Player_Flutter#71]
我直接clone下来，执行了Pub get后，没有改动代码，但是无法编译，参考了这篇文章：https://blog.csdn.net/MrLizuo/article/details/127635511
将FlatButton更改为TextButton后，编译成功，打开app后直播、点播、短视频均无法播放，一直加载中。

请问是更改了TextButton导致的吗？

我的环境：Flutter 3.3.0 ，Tools • Dart 2.18.0

**Comment by Kongdy** [comment]
@qadan72 
1、flutter 3.3.0以上，FlatButton废弃了，改为TextButton，使用Flutter 3.3.0进行开发，就需要手动更改该控件。
2、视频播放能力需要注册license并在代码中设置才可以使用，详情可以参考文档 https://github.com/LiteAVSDK/Player_Flutter/blob/main/Flutter/docs/%E9%9B%86%E6%88%90%E6%8C%87%E5%BC%95.md#%E9%9B%86%E6%88%90%E8%A7%86%E9%A2%91%E6%92%AD%E6%94%BE-license
