### ISSUE TITLE
setRenderMode API 不支持？

### ISSUE THREAD

**Issue by YougaKing** [LiteAVSDK/Player_Flutter#74]
// RENDER_MODE_FILL_SCREEN    = 0,    ///< 图像铺满屏幕，不留黑边，如果图像宽高比不同于屏幕宽高比，部分画面内容会被裁剪掉。
    // RENDER_MODE_FILL_EDGE      = 1,    ///< 图像适应屏幕，保持画面完整，但如果图像宽高比不同于屏幕宽高比，会有黑边的存在。
    void setRenderMode(int mode) {
        if (mVodPlayer != null) {
            mVodPlayer.setRenderMode(mode);
        }
    }
目前是画面被拉伸了

**Comment by Kongdy** [comment]
@YougaKing 由于视频是渲染在flutter画布上，所以播放器SDK的接口无法控制flutter画布的渲染比例，可以仿照播放器组件的做法，通过控制Texture的大小，来控制画面在父布局中展示的比例

**Comment by YougaKing** [comment]
搞定了，感谢大佬

**Comment by MrUncleX** [comment]
> 搞定了，感谢大佬

兄弟，实现的代码方便分享一下吗

**Comment by MrUncleX** [comment]
> 来控制画面在父布局中展示的比例

有没有实现例子
