### ISSUE TITLE
FTXDownloadManager.java:209: 错误: 不兼容的类型: 从long转换到int可能会有损失

### ISSUE THREAD

**Issue by YougaKing** [LiteAVSDK/Player_Flutter#77]
.pub-cache/git/Player_Flutter-92f8d3b197482bd4af1c6cc88371a7228710006e/Flutter/android/src/main/java/com/tencent/vod/flutter/FTXDownloadManager.java:209: 错误: 不兼容的类型: 从long转换到int可能会有损失
        bundle.putInt("size", mediaInfo.getSize());
                                               ^
.pub-cache/git/Player_Flutter-92f8d3b197482bd4af1c6cc88371a7228710006e/Flutter/android/src/main/java/com/tencent/vod/flutter/FTXDownloadManager.java:210: 错误: 不兼容的类型: 从long转换到int可能会有损失
        bundle.putInt("downloadSize", mediaInfo.getDownloadSize());

**Comment by Kongdy** [comment]
@YougaKing 更新目前最新版本即可

**Comment by itlws** [comment]
> @YougaKing 更新目前最新版本即可

遇到同样的问题，未更新之前是没问题的；怎么更新到目前最新版本？
