### ISSUE TITLE
android默认会监听屏幕亮度，导致进入应用程序，亮度被调高。需要改为可配置是否监听

### ISSUE THREAD

**Issue by lzhAndroid** [LiteAVSDK/Player_Flutter#80]
<img width="839" alt="image" src="https://user-images.githubusercontent.com/1432552/229022096-c70516a3-6f99-47fd-8512-6042606455ed.png">

**Comment by lzhAndroid** [comment]
[
<img width="839" alt="image" src="https://user-images.githubusercontent.com/1432552/229021498-5de453a6-a31d-4b76-b503-8d2a2bdd959a.png">
](url)

**Comment by Kongdy** [comment]
@lzhAndroid 回到app会优先根据系统亮度对齐，可以依赖main或者professional最新代码验证

**Comment by lzhAndroid** [comment]
> @lzhAndroid 回到app会优先根据系统亮度对齐，可以依赖main或者professional最新代码验证

小米手机上测试了，还是不行，操作步骤是播放，然后home掉，修改系统亮度，进入应用后，亮度又还原成之前的亮度了。我们希望这个亮度完全跟随系统，因为用户没有操作过播放器相关的亮度

**Comment by Kongdy** [comment]
@lzhAndroid 请确认是否更新到最新代码，包括superPlayer_widget的flutter代码，可以使用最新的demo验证下，目前从桌面回到app是优先对齐系统亮度的
