### ISSUE TITLE
libdownloadproxy.so SIGABRT

### ISSUE THREAD

**Issue by YougaKing** [LiteAVSDK/Player_Flutter#81]
flutter 项目，版本号：release_player_v11.0.0
1
#00 pc 000000000005205c /apex/com.android.runtime/lib64/bionic/libc.so (abort+164)
2
#01 pc 0000000000053e00 /apex/com.android.runtime/lib64/bionic/libc.so
3
#02 pc 00000000000b4e7c /apex/com.android.runtime/lib64/bionic/libc.so
4
#03 pc 00000000000b4cb4 /apex/com.android.runtime/lib64/bionic/libc.so (pthread_mutex_lock+156)
5
#04 pc 00000000000b3200 /apex/com.android.runtime/lib64/bionic/libc.so (pthread_cond_timedwait+168)
6
#05 pc 0000000000091c20 /data/app/~~dlUBptE0BnelhmQ_s9BCPg==/com.longnanming.musclefitness-08o9VuuIzfn-3mvGnkDcHA==/lib/arm64/libdownloadproxy.so
7
#06 pc 0000000000093028 /data/app/~~dlUBptE0BnelhmQ_s9BCPg==/com.longnanming.musclefitness-08o9VuuIzfn-3mvGnkDcHA==/lib/arm64/libdownloadproxy.so
8
#07 pc 000000000009369c /data/app/~~dlUBptE0BnelhmQ_s9BCPg==/com.longnanming.musclefitness-08o9VuuIzfn-3mvGnkDcHA==/lib/arm64/libdownloadproxy.so
9
#08 pc 00000000000937a4 /data/app/~~dlUBptE0BnelhmQ_s9BCPg==/com.longnanming.musclefitness-08o9VuuIzfn-3mvGnkDcHA==/lib/arm64/libdownloadproxy.so
10
#09 pc 00000000000b3ea0 /apex/com.android.runtime/lib64/bionic/libc.so
11
#10 pc 0000000000053880 /apex/com.android.runtime/lib64/bionic/libc.so

**Comment by Kongdy** [comment]
@YougaKing 建议更新到目前最新SDK后，尝试下是否还会复现

**Comment by Kongdy** [comment]
长时间未回复，issue关闭
