### ISSUE TITLE
'value >= min && value <= max'

### ISSUE THREAD

**Issue by gjrcoding** [LiteAVSDK/Player_Flutter#86]
The following assertion was thrown building SuperPlayerMoreView-[LabeledGlobalKey<_SuperPlayerMoreViewState>#4da09](dirty, state: _SuperPlayerMoreViewState#5a60b):
Value 1.600000023841858 is not between minimum 0.0 and maximum 1.0
'package:flutter/src/material/slider.dart':
slider.dart:1
Failed assertion: line 166 pos 15: 'value >= min && value <= max'

**Comment by Kongdy** [comment]
@gjrcoding 已修复
