### ISSUE TITLE
loading 很久，onPlayerEventBroadcast 没有没收到任何事件

### ISSUE THREAD

**Issue by YougaKing** [LiteAVSDK/Player_Flutter#89]
配置如下。   
FTXVodPlayConfig playConfig = FTXVodPlayConfig();
    playConfig.connectRetryCount = 1;
    playConfig.connectRetryInterval = 0;
    playConfig.progressInterval = 100;

长达3、4分钟loading, onPlayerEventBroadcast 没有没收到任何事件，重试的机制是否有问题？

**Comment by Kongdy** [comment]
@YougaKing connectRetryInterval 设置一个不为0的值试试

**Comment by YougaKing** [comment]
await setLoop(loop);
    await setMute(mute);
    if (startTime > 0) {
      await setStartTime(startTime);
    }
    await enableHardwareDecode(true);
    FTXVodPlayConfig playConfig = FTXVodPlayConfig();
    playConfig.connectRetryCount = 1;
    playConfig.connectRetryInterval = 1;
    playConfig.progressInterval = 100;

    /// 设为true，可平滑切换码率, 设为false时，可提高多码率地址打开速度
    playConfig.smoothSwitchBitrate = true;

    /// 如果不配置preferredResolution，则在播放多码率视频的时候优先播放720 * 1280分辨率的码率
    /// 播放 HLS 的多码率视频源，如果你提前知道视频流的分辨率信息，可以在启播前优先指定播放的视频分辨率。 播放器会查找小于或等于偏好分辨率的流进行启播，启播后没有必要再通过 setBitrateIndex 切换到需要的码流。
    playConfig.preferredResolution = TencentPlayer.preferredResolution();
    playConfig.enableAccurateSeek = true; // 设置是否精确 seek，默认 true
    setConfig(playConfig);


设置后还是收到任何事件。

**Comment by Kongdy** [comment]
@YougaKing 那就是一直都没有正常播放？有没有正确设置license？

**Comment by Kongdy** [comment]
长时间未回复，关闭issue
