### ISSUE TITLE
有一个视频总是提示音频解码失败,这个有什么办法吗?

### ISSUE THREAD

**Issue by hpp0hpp** [LiteAVSDK/Player_Flutter#91]
链接如下, 可能过几天失效.
> http://otttv.bj.chinamobile.com/PLTV/88888888/224/3221226465/index.m3u8?zoneoffset=0&servicetype=1&icpid=&limitflux=-1&limitdur=-1&tenantId=8601&accountinfo=%7E%7EV2.0%7EHvHtbZqR3g3ClvTFBTBJ3Q%7EEfGlEzYbs-jOaaObX6ex4Xz1PKsszYWB17Guj4XhWw2h53ipvWb154lXOASLfzSW%7EExtInfo9bj61dxzlMXrsixrqcFYPg%3A20230705233119%2C6745527%2C120.244.162.241%2C20230705233119%2C10000100000000050000000003870752%2C6745527%2C-1%2C0%2C1%2C%2C%2C2%2C2201300%2C%2C%2C2%2C%2C10000100000000060000000007251136_0%2CEND&GuardEncType=2&it=H4sIAAAAAAAAAE2Oyw6CMBRE_6bLhhZ5LbrSmJgYNAHdmkt7qYRCsQUS_14gLFzO5JzJjA4kXk4iDnnKOKZVVWWHOghTXieKKZA8giRgEfH4ya3gRIIxTa9zq1btWRxfLOOUxSnlYUajiJTr4tmAFsEG51NXodvDYhbo5kaiUL6mM3gKWjvUMDa2p3cD34czO0Kw3N_1kzFkXEMJvl0K8gZ_tN0ADtXV6o0TNRiPZADZgsYcOvzzbk4tJ37DMk7I7gAAAA

**Comment by Kongdy** [comment]
@hpp0hpp 链接无法访问，502

**Comment by Kongdy** [comment]
@hpp0hpp 查看该视频的音频格式为mp2，目前无法支持，建议将视频源码转码再进行尝试

**Comment by hpp0hpp** [comment]
@Kongdy 
为什么不考虑支持mp2格式的音频?
