### ISSUE TITLE
横屏有bug

### ISSUE THREAD

**Issue by kuma0605** [LiteAVSDK/Player_Flutter#92]
点击横屏，andriod/ios都报错

**Comment by Kongdy** [comment]
@kuma0605 麻烦贴出报错信息

**Comment by kuma0605** [comment]
<img width="1409" alt="截屏2023-07-12 10 17 46" src="https://github.com/LiteAVSDK/Player_Flutter/assets/2958589/488209eb-dab4-4133-9976-db7cc65b21c1">

**Comment by Kongdy** [comment]
@kuma0605 这是一个会在界面绘制完成后的一次性执行任务，监听到界面绘制完成后开始刷新界面调整播放器比例，此时发现组件已经dispose了，有两个点你可以检查下：
1、是否有监听superPlayerWidget的全屏进出事件，并在事件中执行了组件销毁等逻辑
2、superPlayerWidget的全屏播放器是一个全新的page，进入全屏/横屏的时候，组件会push一个新页面，然后视频会在新页面播放，退出全屏，会pop掉这个page，可以检查下是否对播放器界面当前生命周期的暂停周期等做了监听，并在监听中执行了销毁方法。

**Comment by kuma0605** [comment]
`// Copyright (c) 2022 Tencent. All rights reserved.
import 'dart:async';
import 'dart:convert';
import 'dart:developer';

import 'package:flutter/material.dart';
import 'package:flutter_easyloading/flutter_easyloading.dart';
import 'package:go_router/go_router.dart';

import 'package:super_player/super_player.dart';
import '../http.dart';
import 'package:superplayer_widget/demo_superplayer_lib.dart';

import '../screen_adaptive/int_extension.dart';

/// flutter superplayer demo
class DemoSuperPlayer extends StatefulWidget {
  Map? initParams = {};

  DemoSuperPlayer({this.initParams});

  @override
  State<StatefulWidget> createState() => _DemoSuperPlayerState();
}

// class _DemoSuperPlayerState extends State<DemoSuperPlayer> with TXPipPlayerRestorePage {
class _DemoSuperPlayerState extends State<DemoSuperPlayer> {
  Timer? timerMark;
  Map videoInfo = {
    "name": "",
    "coverUrl": "",
    "mediaUrl": "",
    "studyTime": 0,
    "fileId": "",
    "complete": false,
  };

  static const DEFAULT_PLACE_HOLDER =
      "http://xiaozhibo-10055601.file.myqcloud.com/coverImg.jpg";

  static const ARGUMENT_TYPE_POS = "arg_type_pos";
  static const ARGUMENT_VIDEO_DATA = "arg_video_data";

  List<SuperPlayerModel> videoModels = [];
  bool _isFullScreen = false;
  late SuperPlayerController _controller;
  SuperVodDataLoader loader = SuperVodDataLoader();
  StreamSubscription? simpleEventSubscription;
  // int tabSelectPos = 0;
  SuperPlayerModel? currentVideoModel;
  SuperPlayerModel? initVideoModel;
  double? initStartTime;
  TextStyle _textStyleSelected =
      new TextStyle(fontSize: 16, color: Colors.white);
  TextStyle _textStyleUnSelected =
      new TextStyle(fontSize: 16, color: Colors.grey);

  @override
  void initState() {
    super.initState();
    // 监听设备旋转
    SuperPlayerPlugin.startVideoOrientationService();
    _controller = SuperPlayerController(context);

    // TXPipController.instance.setPipPlayerPage(this);
    FTXVodPlayConfig config = FTXVodPlayConfig();
    // 如果不配置preferredResolution，则在播放多码率视频的时候优先播放720 * 1280分辨率的码率
    config.preferredResolution = 720 * 1280;
    _controller.setPlayConfig(config);
    simpleEventSubscription =
        _controller.onSimplePlayerEventBroadcast.listen((event) {
      String evtName = event["event"];
      if (evtName == SuperPlayerViewEvent.onStartFullScreenPlay) {
        // enter fullscreen
      } else if (evtName == SuperPlayerViewEvent.onStopFullScreenPlay) {
        // exit fullscreen
      } else {
        print("播放事件监听$evtName");
      }

      if (evtName == SuperPlayerViewEvent.onSuperPlayerDidEnd) {
        //播放结束
        timerMark?.cancel();
        if(!_controller.canDrag)_controller.canDrag=true;
        _doComplete();
      }

      if (evtName == SuperPlayerViewEvent.onSuperPlayerBackAction) {
        //返回
      }
    });
    if (null != widget.initParams) {
      // tabSelectPos = widget.initParams![ARGUMENT_TYPE_POS];
      initVideoModel = widget.initParams![ARGUMENT_VIDEO_DATA];
      // initStartTime =  widget.initParams![TXPipController.ARGUMENT_PIP_START_TIME];
    }
    /*if (tabSelectPos == 0) {
      _getLiveListData();
    } else if (tabSelectPos == 1) {
      _getVodListData();
    }*/
    // _getMyVodListData(widget.initParams!["fileId"]);
    // _getVodListData();
    // _getMyVodListData("243791579044409707");
    // _getMyVideoListData(widget.initParams!["fileId"]);

    //获取播放视频信息，title、播放进度等

    _doCount();
    // Future.delayed(Duration.zero,(){
    _getVideoData(widget.initParams!["kpointId"]);
    // });
  }

  Future _doCount() async {
    try {
      dynamic courseId = widget.initParams!["courseId"];
      dynamic kpointId = widget.initParams!["kpointId"];
      dynamic response = await DioApi.get("/webapp/addCourseStudyNum",
          queryParameters: {
            "courseId": courseId,
            "kpointId": kpointId,
            "watchType": 0
          });

      log(jsonEncode(response), name: "详情计数器");

      return response;
    } catch (e) {
      print(e);
    }
  }

  Future _getVideoData(kpointId) async {
    try {
      dynamic response = await DioApi.get("/webapp/getVideoInfo",
          queryParameters: {"kpointId": kpointId});

      log(jsonEncode(response), name: "视频详情");

      if (response['success']) {
        Map entity = response["entity"];
        dynamic mbi = entity["mbi"];
        videoInfo["studyTime"] = entity["studyTime"];
        videoInfo["name"] = mbi["name"];
        videoInfo["coverUrl"] = mbi["coverUrl"];
        videoInfo["mediaUrl"] = entity["transcodeUrl"]??mbi["mediaUrl"];
        videoInfo["fileId"] = mbi["vid"];
        videoInfo["complete"] = entity["complete"];

        _controller.canDrag=videoInfo["complete"];

        _getMyVideoListData();
        // _getMyVodListData();
      }

      return response;
    } catch (e) {
      print(e);
    }
  }

  _recordDuration() {
    const fiveSeconds = Duration(seconds: 10);
    // _fetchData() is your function to fetch data
    timerMark = Timer.periodic(fiveSeconds, (Timer t) => _doRecord());
  }

  _doRecord() async {
    try {
      dynamic courseId = widget.initParams!["courseId"];
      dynamic kpointId = widget.initParams!["kpointId"];
      dynamic duration = _controller.currentDuration.toStringAsFixed(0);
      print('课程id $courseId $kpointId $duration');
      dynamic response = await DioApi.get("/webapp/addCourseStudyTime",
          queryParameters: {
            "courseId": courseId,
            "kpointId": kpointId,
            "studyTime": duration
          });

      return response;
    } catch (e) {
      print(e);
    }
  }

  _doComplete() async {
    try {
      dynamic courseId = widget.initParams!["courseId"];
      dynamic kpointId = widget.initParams!["kpointId"];
      print('课程id $courseId $kpointId ');
      dynamic response =
          await DioApi.get("/webapp/studyComplete", queryParameters: {
        "courseId": courseId,
        "kpointId": kpointId,
      });

      log(jsonEncode(response), name: "播放结束");

      if (response['success']) {
        Map entity = response["entity"];
      }

      return response;
    } catch (e) {
      print(e);
    }
  }

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
        onWillPop: onWillPop,
        child: Container(
          decoration: const BoxDecoration(
              image: DecorationImage(
            image: AssetImage("images/ic_new_vod_bg.png"),
            fit: BoxFit.cover,
          )),
          child: Scaffold(
            backgroundColor: Colors.transparent,
            appBar: _isFullScreen
                ? null
                : AppBar(
                    backgroundColor: Colors.transparent,
                    centerTitle: true,
                    title:  Text('课程学习',style: TextStyle(
                      fontSize: 14.px
                    ),),
                    leading:IconButton(
                        iconSize: 14.px,
                        onPressed: (){
                          // Navigator.of(context).pop();
                          context.pop();
                        },
                        icon: const Icon(
                          // color:Colors.blueAccent,
                            Icons.arrow_back_ios
                        )
                    ),
                  ),
            body: SafeArea(
              child: Builder(
                builder: (context) => getBody(),
              ),
            ),
          ),
        ),
        );
  }

  Future<bool> onWillPop() async {
    return !_controller.onBackPress();
  }

  /*Widget getTabRow() {
    return new Container(
      // hide by dylan, it will lead overflow
      // height: 40,
      child: new Row(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        children: [
          new GestureDetector(
            child: new Container(
              child: Text(
                "直播",
                style: tabSelectPos == 0
                    ? _textStyleSelected
                    : _textStyleUnSelected,
              ),
            ),
            onTap: _getLiveListData,
          ),
          new GestureDetector(
              onTap: _getVodListData,
              child: new Container(
                child: Text(
                  "点播",
                  style: tabSelectPos == 1
                      ? _textStyleSelected
                      : _textStyleUnSelected,
                ),
              )),
        ],
      ),
    );
  }*/

  Widget getBody() {
    return Column(
      children: [
        _getPlayArea(),
        Expanded(flex: 1, child: _getListArea()),
        // _getAddArea()
      ],
    );
  }

  Widget _getPlayArea() {
    return Container(
      decoration: BoxDecoration(color: Colors.black),
      height: 220,
      child: SuperPlayerView(_controller),
    );
  }

  Widget _getListArea() {
    return Container(
        // margin: EdgeInsets.only(top: 10),
        child: Column(
      mainAxisAlignment: MainAxisAlignment.start,
      children: [
        Container(
          margin: EdgeInsets.only(top: 10.px),
          child: Text(widget.initParams!["title"],style: TextStyle(
            color:Colors.white,
            fontSize: 14.px
          ),),
        )
        // getTabRow(),
        // Container(),
        /*ElevatedButton(
          child: Text("获取播放时间"),
          onPressed: () {
            dynamic currentDuration = _controller.currentDuration;
          },
        ),*/
        //隐藏播放列表，因为每次进入该widget，会对应传入fileId，所以只有一个视频 by 丁超
        /*Expanded(
            child: ListView.builder(
          shrinkWrap: true,
          itemCount: videoModels.length,
          itemBuilder: (context, i) => _buildVideoItem(videoModels[i]),
        ))*/
      ],
    ));
  }

  Widget _buildVideoItem(SuperPlayerModel playModel) {
    return Column(
      children: [
        ListTile(
          leading: Image.network(
            playModel.coverUrl.isEmpty
                ? DEFAULT_PLACE_HOLDER
                : playModel.coverUrl,
            width: 100,
            height: 60,
            fit: BoxFit.cover,
            alignment: Alignment.center,
          ),
          title: new Text(
            playModel.title,
            style: TextStyle(color: Colors.white),
          ),
          onTap: () => playCurrentModel(playModel, 0),
          horizontalTitleGap: 10,
        ),
        Divider()
      ],
    );
  }

  /*Widget _getAddArea() {
    return Container(
      height: 50,
      child: IconButton(
          icon: new Image.asset('images/addp.png'),
          onPressed: () => {onAddVideoTap(context)}),
    );
  }

  void onAddVideoTap(BuildContext context) {
    bool isLive = tabSelectPos == 0;
    showDialog(
        context: context,
        builder: (context) {
          return DemoInputDialog(
            "",
            0,
            "",
            (String url, int appId, String fileId, String pSign) {
              SuperPlayerModel model = new SuperPlayerModel();
              model.appId = appId;
              if (url.isNotEmpty) {
                model.videoURL = url;
              } else if (appId != 0 && fileId.isNotEmpty) {
                model.videoId = new SuperPlayerVideoId();
                model.videoId!.fileId = fileId;
                if (pSign.isNotEmpty) {
                  model.videoId!.psign = pSign;
                }
              } else {
                EasyLoading.showError("请输入播放地址!");
                return;
              }

              loader.getVideoData(model, (resultModel) {
                setState(() {
                  videoModels.add(resultModel);
                });
                playCurrentModel(resultModel, 0);
              });
            },
            needPisgn: !isLive,
            showFileEdited: !isLive,
          );
        });
  }*/

  void playCurrentModel(SuperPlayerModel model, double startTime) {
    currentVideoModel = model;
    _controller.setStartTime(startTime);
    _controller.playWithModelNeedLicence(model);
  }

  void playVideo(SuperPlayerModel model) {
    if (null != initVideoModel) {
      playCurrentModel(initVideoModel!, initStartTime ?? 0);
      initVideoModel = null;
      initStartTime = null;
    } else {
      playCurrentModel(model, 0);
    }
  }

  void _getLiveListData() async {
    /*setState(() {
      tabSelectPos = 0;
    });*/
    List<SuperPlayerModel> models = [];

    int playAction = SuperPlayerModel.PLAY_ACTION_AUTO_PLAY;
    SuperPlayerModel model = SuperPlayerModel();
    model.title = "测试视频";
    model.videoURL =
        "http://liteavapp.qcloud.com/live/liteavdemoplayerstreamid_demo1080p.flv";
    model.coverUrl =
        "http://1500005830.vod2.myqcloud.com/6c9a5118vodcq1500005830/66bc542f387702300661648850/0RyP1rZfkdQA.png";
    model.playAction = playAction;
    models.add(model);

    videoModels.clear();
    videoModels.addAll(models);
    setState(() {
      if (videoModels.isNotEmpty) {
        playVideo(videoModels[0]);
      } else {
        EasyLoading.showError("video list request error");
      }
    });
  }

  void _getVodListData() async {
    /*setState(() {
      tabSelectPos = 1;
    });*/
    List<SuperPlayerModel> models = [];

    int playAction = SuperPlayerModel.PLAY_ACTION_AUTO_PLAY;

    SuperPlayerModel model = SuperPlayerModel();
    model.appId = 1500005830;
    model.videoId = new SuperPlayerVideoId();
    model.videoId!.fileId = "8602268011437356984";
    model.title = "云点播（fileId播放）";
    model.playAction = playAction;
    models.add(model);

    model = SuperPlayerModel();
    model.appId = 1252463788;
    model.videoId = new SuperPlayerVideoId();
    model.videoId!.fileId = "5285890781763144364";
    model.title = "腾讯云";
    model.playAction = playAction;
    models.add(model);

    model = SuperPlayerModel();
    model.title = "加密视频播放";
    model.appId = 1254432039;
    model.videoId = new SuperPlayerVideoId();
    model.videoId!.fileId = "5285890816303742312";
    model.videoId!.psign =
        "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6MTI1NDQzMjAzOSwiZmlsZUlkIjoiNTI4NTg5MDgxNjMwMzc0MjMxMiIsImN1cnJlbnRUaW1lU3"
        "RhbXAiOjE2MTcyNTc0ODMsInBjZmciOiJiYXNpY0RybVByZXNldCIsInVybEFjY2Vzc0luZm8iOnt9LCJkcm1MaWNlbnNlSW5mbyI6e319.2H1t9dKPpdA41"
        "a8t1WwI631OWC18HGl60ccBDLylCKE";
    model.playAction = playAction;
    models.add(model);

    model = SuperPlayerModel();
    model.appId = 1252463788;
    model.videoId = new SuperPlayerVideoId();
    model.videoId!.fileId = "4564972819219071568";
    model.playAction = playAction;
    models.add(model);

    model = SuperPlayerModel();
    model.appId = 1252463788;
    model.videoId = new SuperPlayerVideoId();
    model.videoId!.fileId = "4564972819219071668";
    model.playAction = playAction;
    models.add(model);

    model = SuperPlayerModel();
    model.appId = 1252463788;
    model.videoId = new SuperPlayerVideoId();
    model.videoId!.fileId = "4564972819219071679";
    model.playAction = playAction;
    models.add(model);

    model = SuperPlayerModel();
    model.appId = 1252463788;
    model.videoId = new SuperPlayerVideoId();
    model.videoId!.fileId = "4564972819219081699";
    model.playAction = playAction;
    models.add(model);

    List<Future<void>> requestList = [];
    for (SuperPlayerModel tempModel in models) {
      requestList.add(loader.getVideoData(tempModel, (_) {}));
    }

    await Future.wait(requestList);
    videoModels.clear();
    videoModels.addAll(models);
    if (mounted) {
      setState(() {
        if (videoModels.isNotEmpty) {
          playVideo(videoModels[0]);
        } else {
          EasyLoading.showError("video list request error");
        }
      });
    }
  }

  void _getMyVodListData() async {
    try {
      List<SuperPlayerModel> models = [];

      int playAction = SuperPlayerModel.PLAY_ACTION_AUTO_PLAY;

      SuperPlayerModel model = SuperPlayerModel();

      model = SuperPlayerModel();
      model.appId = 1312904669;
      model.videoId = new SuperPlayerVideoId();
      model.videoId!.fileId = videoInfo["fileId"] ?? "243791579044409707";
      model.playAction = playAction;
      models.add(model);

      List<Future<void>> requestList = [];
      for (SuperPlayerModel tempModel in models) {
        requestList.add(loader.getVideoData(tempModel, (_) {}));
      }

      await Future.wait(requestList);
      videoModels.clear();
      videoModels.addAll(models);
      if (mounted) {
        setState(() {
          if (videoModels.isNotEmpty) {
            // playVideo(videoModels[0]);

            print('观看时间 ${videoInfo["studyTime"]}');
            dynamic studyTime = videoInfo["studyTime"];
            studyTime = studyTime.toString();
            studyTime = double.parse(studyTime);
            playCurrentModel(videoModels[0], studyTime);

            _recordDuration();
          } else {
            EasyLoading.showError("video list request error");
          }
        });
      }
    } catch (e) {}
  }

  void _getMyVideoListData() {
    List<SuperPlayerModel> models = [];

    int playAction = SuperPlayerModel.PLAY_ACTION_AUTO_PLAY;
    print("视频播放地址");
    print(videoInfo["mediaUrl"]);
    SuperPlayerModel model = SuperPlayerModel();
    model.title = videoInfo["name"];
    model.videoURL = videoInfo["mediaUrl"];
    model.coverUrl = videoInfo["coverUrl"];
    model.playAction = playAction;
    models.add(model);

    videoModels.clear();
    videoModels.addAll(models);
    setState(() {
      if (videoModels.isNotEmpty) {
        // playVideo(videoModels[0]);
        // playCurrentModel(videoModels[0], videoInfo["studyTime"]);
        // print('观看时间 ${videoInfo["studyTime"]}');
        dynamic studyTime = videoInfo["studyTime"];
        studyTime = studyTime.toString();
        studyTime = double.parse(studyTime);
        playCurrentModel(videoModels[0], studyTime);

        _recordDuration();
      } else {
        EasyLoading.showError("video list request error");
      }
    });
  }

  @override
  void dispose() {
    timerMark?.cancel();

    // must invoke when page exit.
    _controller.releasePlayer();
    simpleEventSubscription?.cancel();
    // restore page brightness
    SuperPlayerPlugin.restorePageBrightness();
    super.dispose();
  }

  /*@override
  void onNeedSavePipPageState(Map<String, dynamic> params) {
  params[ARGUMENT_TYPE_POS] = tabSelectPos;
  params[ARGUMENT_VIDEO_DATA] = currentVideoModel;
  }
  }*/
}
`

**Comment by kuma0605** [comment]
<img width="239" alt="截屏2023-07-12 12 09 09" src="https://github.com/LiteAVSDK/Player_Flutter/assets/2958589/8316c597-91d4-4cdb-87cb-977f1a373bfb">

**Comment by Kongdy** [comment]
@kuma0605 你的demo代码暂时没看出问题，不过superPlayerWidget最近半年基本没有改动，这个目前是必现的还是有一定的复现条件？最近开发环境是否有变动？是否是特定机型的问题？

**Comment by kuma0605** [comment]
@Kongdy 必现的，点击全屏，就会报错。安卓模拟器，iphone真机调试，都会报这个错误。app的表现是跳转到首页了，把首页给横屏了。

**Comment by kuma0605** [comment]
@Kongdy 我拉一个之前的播放器版本试试看。

**Comment by kuma0605** [comment]
@Kongdy 安卓模拟器报错
```dart
======== Exception caught by rendering library =====================================================
The following assertion was thrown during layout:
A RenderFlex overflowed by 376 pixels on the bottom.

The relevant error-causing widget was: 
  Flex Flex:file:///Users/dylan/StudioProjects/jzlearn/lib/screens/login_screen.dart:149:20
The overflowing RenderFlex has an orientation of Axis.vertical.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

The specific RenderFlex in question is: RenderFlex#8d875 OVERFLOWING
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=807.3, h=392.7)
...  size: Size(807.3, 392.7)
...  direction: vertical
...  mainAxisAlignment: start
...  mainAxisSize: max
...  crossAxisAlignment: center
...  verticalDirection: down
◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
====================================================================================================
```

**Comment by kuma0605** [comment]
@Kongdy app表现一致，都跳转到登录页，这我不理解。
<img width="290" alt="截屏2023-07-12 15 17 03" src="https://github.com/LiteAVSDK/Player_Flutter/assets/2958589/9485b1fe-db24-482c-8f92-105846e79fe3">

**Comment by kuma0605** [comment]
@Kongdy 确实是我代码变更引起的。
我做了全局适配。适配代码位置变更，引起全屏问题。

![6071689148340_ pic](https://github.com/LiteAVSDK/Player_Flutter/assets/2958589/15498921-b329-4da9-982b-e36b1689c2fd)

**Comment by kuma0605** [comment]
```dart
// size_fit.dart
// var contextView = MediaQuery.sizeOf(context); 
// 改成下面语句就不会报错了。
var contextView = MediaQueryData.fromView(View.of(context));
```

**Comment by kuma0605** [comment]
感谢帮助定位问题。

**Comment by Kongdy** [comment]
@kuma0605 好的，后续会对这里做规避，防止dispose下执行setState
