### ISSUE TITLE
你好，m3u8加密视频播放不了

### ISSUE THREAD

**Issue by Youngpeoplemood** [LiteAVSDK/Player_Flutter#93]

**Comment by Kongdy** [comment]
@Youngpeoplemood 你好，麻烦提供下无法播放的m3u8加密视频的视频源以及clog日志，我们进行一下排查。clog日志可以参考以下链接进行提取：https://cloud.tencent.com/developer/article/1502366

**Comment by Kongdy** [comment]
@Youngpeoplemood 长时间未回复，issue关闭
