### ISSUE TITLE
请问息屏下载支持吗？支持的话需要配置什么？

### ISSUE THREAD

**Issue by zcb1603999** [LiteAVSDK/Player_Flutter#95]
目前下载已经做好了，但是息屏后下载会被系统断掉，请问息屏下载支持吗？支持的话需要配置什么？

**Comment by Kongdy** [comment]
@zcb1603999 息屏后停掉下载线程是系统行为，建议业务侧采用线程保活、创建前台UI等方式来维持下载线程的存活
