### ISSUE TITLE
ios端，视频会议、直播等页面，在横屏的时候，摄像头画面旋转异常

### ISSUE THREAD

**Issue by lan2000** [LiteAVSDK/Player_Flutter#99]
tencent_trtc_cloud ：2.5.9

```
Flutter (Channel stable, 3.13.8, on Microsoft Windows [版本 10.0.19042.630], locale zh-CN)
    • Flutter version 3.13.8 on channel stable at D:\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter/
    • FLUTTER_GIT_URL = https://github.com/flutter/flutter/
    • Framework revision 6c4930c4ac (11 days ago), 2023-10-18 10:57:55 -0500
    • Engine revision 767d8c75e8
    • Dart version 3.1.4
    • DevTools version 2.25.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

并且ios直接下载demo APP也是同样的情况。
下面是测试是视频，设备是ipad 第七代，系统版本16.4.1

https://github.com/LiteAVSDK/Player_Flutter/assets/29618907/09b7df99-5daa-427d-8a47-0b6b42e6e839

https://github.com/LiteAVSDK/Player_Flutter/assets/29618907/e203dbc4-7033-4fd9-b7e9-d48739f79a20

**Comment by lan2000** [comment]
tencent_trtc_cloud ：2.4.5 版本是正常的，从tencent_trtc_cloud ：2.4.6开始，就出现这个问题了

**Comment by lan2000** [comment]
回退到tencent_trtc_cloud: 2.4.5就恢复正常了，从2.4.6版本开始就出现这个问题

**Comment by Kongdy** [comment]
@lan2000 trtc的业务可以在这里反馈下看看 https://github.com/LiteAVSDK/TRTC_Flutter
